### ISSUE TITLE
Some installing questions

### ISSUE THREAD

**Issue by sonoro1234** [gogins/silencio#1]
I am testing Silencio and have some questions:

1-For using ScoreView: Where should I get this distribution from
```
local gl   =        require("ffi/OpenGL" )
local glu  =        require("ffi/glu")
local glfw =        require("ffi/glfw")
```
2- I got fomus from http://fomus.sourceforge.net/, downloaded the binary for win32 but fomus.exe was not installed. Searched mailing list but last mail is from 2012. Any idea?

3- instaled CSound 6 and SilencioTest.lua posts:
```
error: syntax error, unexpected T_IDENT  (token "fluidEngine") from file SilencioTest.orc (1)
 line 7:
>>>giFluidsynth             fluidEngine  <<<
Unexpected untyped word giFluidsynth when expecting a variable
Parsing failed due to invalid input!
```
Best
victor

**Comment by sonoro1234** [comment]
Question 2 is solved: fomus install fomus.exe in c:/windows/fomus/bin and points PATH to it

**Comment by gogins** [comment]
For 3, you did not install or build the Fluidsynth opcodes for Csound, and/or you do not have the specified SoundFont 2 sample bank in the configured path. You can either just substitute another instrument for the FluidSynth or fix up your FluidSynth situation.
